// packages/modules/alternate-gateway/demo/media/solid-start/src/routes/media-demo.tsx
import { onCleanup, onMount } from "solid-js";
import { createMediaEngine, createMediaAnalytics } from "@mframework/alternate-media";
import "@mframework/alternate-media/styles/media.css";

export default function MediaDemoPage() {
  let videoEl: HTMLVideoElement | undefined;

  onMount(() => {
    if (!videoEl) return;

    const engine = createMediaEngine({ player: "videojs" });
    const player = engine.mount(videoEl);
    player.loadSource("https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8");

    const analytics = createMediaAnalytics(player, (event) => {
      console.log("[solid-start media analytics]", event);
    });

    onCleanup(() => {
      analytics.dispose();
      player.dispose();
    });
  });

  return (
    <main style={{ "max-width": "900px", margin: "2rem auto", padding: "0 1rem" }}>
      <h1>alternate-media demo (Solid Start)</h1>
      <video ref={videoEl} class="alt-media-player" controls playsInline />
    </main>
  );
}

// packages/modules/alternate-gateway/demo/media/next-js/app/media-demo/page.tsx
"use client";

import { useEffect, useRef } from "react";
import { createMediaEngine, createMediaAnalytics } from "@mframework/alternate-media";
import "@mframework/alternate-media/styles/media.css";

const DEMO_SRC = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8";

export default function MediaDemoPage() {
  const videoRef = useRef<HTMLVideoElement | null>(null);

  useEffect(() => {
    if (!videoRef.current) return;

    const engine = createMediaEngine({ player: "videojs" });
    const player = engine.mount(videoRef.current);
    player.loadSource(DEMO_SRC);

    const analytics = createMediaAnalytics(player, (event) => {
      console.log("[next-js media analytics]", event);
    });

    return () => {
      analytics.dispose();
      player.dispose();
    };
  }, []);

  return (
    <main style={{ maxWidth: 900, margin: "2rem auto", padding: "0 1rem" }}>
      <h1>alternate-media demo (Next.js)</h1>
      <video ref={videoRef} className="alt-media-player" playsInline controls />
    </main>
  );
}
